### ISSUE TITLE
ghost column added

### ISSUE THREAD

**Issue by basilcronus** [asafdav/ng-csv#10]
There is a column added to my export with "garbage data" in it.  When I look the array I'm passing in, it appears clean, and does not contain this additional data in it.  An example of the added data.... 29,02B,02D,02F,02H,02J and some are right justified and others left justified.

**Comment by evilaliv3** [comment]
@asafdav: Actually in current release i still get $$hashKey column added to the exported csv file.
If there anything you could suggest to get around this?
