### ISSUE TITLE
Add commonjs package manager support 

### ISSUE THREAD

**Issue by alexilyaev** [asafdav/ng-csv#119]
Can we add support for loading the ngCsv as a CommonJS module?

See example of Angular UI-Router:
https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js

This will allow doing:
```js
var ngCsv = require('ng-csv');

angular.module('admin', [
    ngCsv
])
```

Instead of hard coding the module name.

**Comment by asafdav** [comment]
Sounds like a great idea, would you like to pull request ?

**Comment by alexilyaev** [comment]
Cool, when can we expect it to be on NPM?

**Comment by asafdav** [comment]
Now :) I'd appreciate it if you could report back that it works well for you.

**Comment by alexilyaev** [comment]
Confirmed.

**Comment by asafdav** [comment]
Great thank you!
