### ISSUE TITLE
Breaking values into individual columns

### ISSUE THREAD

**Issue by Duovili** [asafdav/ng-csv#125]
I am running the example code but I get all my value in one column divided by a comma. How do you separate them into different columns.

**Comment by shaohaolin** [comment]
@Duovili Could you provide a screen shot or an example to explain what you want to achieve?

**Comment by Duovili** [comment]
I realised that the user needs to build it themselves Everything works great thanks for the code.

**Comment by shaohaolin** [comment]
Good to hear! You can close the issue now.

**Comment by thierryskoda** [comment]
I have the same issue, what do you mean by "the user needs to build it themselves" ? @Kratos-SA  It works for me with my excel 2016, but with another computer and different version of excel, it puts all my data in on column divided by a comma.

Thank you for the help!
