### ISSUE TITLE
Doesn't Work with Angularjs 1.4.7

### ISSUE THREAD

**Issue by cpitzak** [asafdav/ng-csv#128]
I took the demo and used angularjs 1.4.7 and angular-sanatize 1.4.7 and there are injection errors. I posted the fiddle here: https://jsfiddle.net/3c46b4p3/

Thanks

**Comment by shaohaolin** [comment]
@cpitzak Please update the latest ng-csv file.
This one is working. https://jsfiddle.net/3c46b4p3/1/

**Comment by asafdav** [comment]
see #129
