### ISSUE TITLE
HashKey appears in CSV output

### ISSUE THREAD

**Issue by mdhari** [asafdav/ng-csv#14]
Hiya,

I'm noticing that the $$hashKey that AngularJS uses to quickly sort/filter the data structure is being included in the CSV output. I introduced one line between lines 133-137 to take it out:

```
angular.forEach(row, function(field, key)
                  {
                    if(key !== "$$hashKey")
                        this.push(field);
                  }, infoArray);
```

I'm sure you can introduce this if statement probably at a better spot that conforms to your flow.

**Comment by evilaliv3** [comment]
@asafdav: Actually in current release i still get $$hashKey column added to the exported csv file.
If there anything you could suggest to get around this?

**Comment by evilaliv3** [comment]
i;ve currently got around this issue by using angular copy before using ng-repeat
