### ISSUE TITLE
Issue with French accented characters like é and à

### ISSUE THREAD

**Issue by ratnofun** [asafdav/ng-csv#174]
When I am exporting to CSV using this directive the french accented characters are coming like Ã which means it is taking as UTF8. If the encoding is set to ANSI ideally this should work. Please note that I am using a button. Also we have tried to use charset attribute but still it does not work

Something like below line normally works when using anchor tags
data:text/csv;charset=utf-8,%EF%BB%BF

**Desired Output** : Numéro d'employeur;Date de mise à jour annuelle;Numéro de police
**Actual Output :** NumÃ©ro d'employeur;Date de mise Ã  jour annuelle;NumÃ©ro de police

**Comment by ratnofun** [comment]
![
![french issue](https://cloud.githubusercontent.com/assets/20594659/17052535/87e2edea-501b-11e6-95f0-0a92f6bf04de.PNG)

**Comment by blotkevin** [comment]
Use add-bom="true" if you want special characters

**Comment by ratnofun** [comment]
thanks it worked
