### ISSUE TITLE
How do make buildCsv wait while I'm loading data asynchronously?

### ISSUE THREAD

**Issue by langman66** [asafdav/ng-csv#19]
I'm not sure if I've setup this directive correctly or not.  Can you please provide some guidance.

In my case when a user clicks the button I will fetch all my data (15,000+ rows) from a WebAPI.  

I've setup my html and controller as such below:

```
            <button class="btn btn-default"
                    ng-csv="getArray()" csv-header="getHeader()" lazy-load="true" filename="export1.csv" field-separator=",">
                Export to CSV (Lazy Load)
            </button>
```

In my getArray() function I'm return a function to be called later to lazy-load my data.

```
    $scope.getArray = function() {
        return lazyLoadExportData;
    }

    function lazyLoadExportData() {

        var deferred = $q.defer();
        getGroupMembers()
            .then(function (data) {
                deferred.resolve(data);
            }, function (errorData) {
            deferred.reject(errorData);
        });
        return deferred.promise;
    }
```

Inside of ng-csv (line 118) the arrData = data() invokes my lazyLoadExportData(), but it does not wait until the lazyLoadExportData() has completed gathering all it's data when the promise is resolved.

 if (angular.isArray(data))
                arrData = data;
              else
                arrData = data();

Can you please provide an example?

Thanks so much!

**Comment by cicw** [comment]
Hi,
Can you help me a litle bit on this too? I think I´m in the "kind of" same situation: :-)

** Code from view
<div><a href="return:void(0)" ng-csv="buildLab()" lazy-load="true" filename="lab.csv" >Lab</a></div>

** Js Code
$scope.buildLab = function() {
            return exportService.getCustomers().then(function(data){
                return data.data
            })
        }

As I can see buildLab is downloading the file before the promise returns the data.

am I missing something obvious here? 

thank´s

**Comment by andy-dumbell** [comment]
Hi there, could you share a JS example of the asynchronous lazy load? BR, Andy
