### ISSUE TITLE
generate object

### ISSUE THREAD

**Issue by rahutwr33** [asafdav/ng-csv#216]
![ngcsv](https://user-images.githubusercontent.com/18547212/30639522-db1c0e7e-9e1c-11e7-9d4f-6c4bf1867f04.png)
![ngcsv](https://user-images.githubusercontent.com/18547212/30639532-e6ed9664-9e1c-11e7-876e-69c40db66f24.png)

**Comment by ptitdje45** [comment]
Did you solve it ?

**Comment by rahutwr33** [comment]
closed.
