### ISSUE TITLE
IE Compatibility

### ISSUE THREAD

**Issue by mcadelago** [asafdav/ng-csv#3]
Nice little directive! However, it doesn't seem to be working in internet explorer at the moment. Is there any plan to modify it to work for IE?

**Comment by Rmabini** [comment]
Hi BerangereMartin,

Can you provide as a plunker , on how to used code , you have provided 

Thanks

**Comment by chaitujil** [comment]
Same issue here. I am trying to use this directive in IE9. Doesn't work. Can someone post a plunker with the hack they did to make it work?

**Comment by BerangereMartin** [comment]
See my pull request i am sorry but no Time to make a plunker

**Comment by lcampanis** [comment]
Is this fix being merged soon? 
Otherwise I'd be happy to provide a new pull request. We've made it work in IE9 as well.
