### ISSUE TITLE
Can we use json key as header instead of defining individual header on csv-header. How do we pass dynamic header according to data assigned to ng-csv ?

### ISSUE THREAD

**Issue by trpansh** [asafdav/ng-csv#52]
Can we use header from the data "downloadProjects" on csv-header instead of "['Field A', 'Field B', 'Field C', 'Field D', 'Field E']" and how do we do it?

**Comment by andrewboni** [comment]
I'd also like something like this- where the key of an object becomes the column header. By loading the `csv-header` separately with something like `Object.keys()` like you mentioned, there is no order guarantee:
```
// array like object with random key ordering
var an_obj = { 100: 'a', 2: 'b', 7: 'c' };
console.log(Object.keys(an_obj)); // console: ['2', '7', '100']
```
