### ISSUE TITLE
CSV from controller - how to specify file?

### ISSUE THREAD

**Issue by axewelder** [asafdav/ng-csv#55]
I see in issue  Exporting from controller #35 (closed), how to drive the action from the controller:

I use the example code show in the issue:

//inject CSV service in your controller
$scope.getArray = [{a: 1, b:2}, {a:3, b:4}];
$scope.options = {};
$scope.options.header = ['Field A', 'Field B'];

$scope.send_email = function() {
        CSV.stringify($scope.getArray, $scope.options).then(function(result){
            console.log(result);
        });
}

The results look correct in the console, but I don't see how I pass in the desired file name and have the file created, like I do in the method from the HTML.

**Comment by HTIRLANGI** [comment]
Hi asafdav, when I use the directive, <a href="" ng-click="nav(info.id, info.name)" ng-csv="export"  filename="{{info.displayName}}.csv">{{info.name}}{{info.displayName}}</a>
I want to control or trigger ng-csv based on a condition. If that condition fails/ is false, then ng-csv should not be triggered and file download should not happen. How can I control this while using nd-csv directive?

**Comment by roccomuso** [comment]
+1

**Comment by ibrychgo** [comment]
Thank you taking the time to post this. I don't have it working all the way...but you probably saved me HOURS getting to this point. :)

**Comment by enjoiful** [comment]
This is possible.  Create a hidden button in your html that has the ng-csv attribute.  Then from your Angular1 controller, click the hidden button like so:

$timeout(function() {
	angular.element('#exportButton').triggerHandler('click');
});
https://stackoverflow.com/questions/22447374/how-to-trigger-ng-click-angularjs-programmatically

<button id="exportButton" ng-csv="exportStuff()" filename= "{{filename}}" hidden></button>
