### ISSUE TITLE
Set dynamic headers

### ISSUE THREAD

**Issue by RobinBorresen** [asafdav/ng-csv#69]
It is possible to set the header with the csv-header attribute on the element. It would be realy great if it was possible to set this header on click event rather when the element is loaded in the DOM.
1. Example
   I would like to use ng-csv as a service. Pas an object array to the service and trigger the csv document creation. But I can't do this with headers at this moment.
2. Example
   Applications using ng-translate for language support won't be able to use the header as its unkown how to write the header when the js comes from the server. Therefor you can't hard-code the header for the "name"-column, 
   eg. "Name", "Navn", "Nombre"

**Comment by slaveofcode** [comment]
@RobinGulbrandsen it could automatically use the key of json values to be the header name with passing `csv-label="true"` on the element
