### ISSUE TITLE
Seems to be broken

### ISSUE THREAD

**Issue by jonny2779** [asafdav/ng-csv#80]
http://ngmodules.org/modules/ng-csv

This plunker example does not work. Tried it locally but failed to get it working.

```
  <button type="button" ng-csv="getArray" filename="test.csv">Export</button>
```

```
$scope.getArray = function () {
    return [2,3,3];
  };
```

**Comment by jonny2779** [comment]
Plunker here: http://jsfiddle.net/asafdav/dR6Nb/

**Comment by asafdav** [comment]
Hi, this Plunker is out of date, where did you find it ? 

For an updated example, please check out the README file.

**Comment by jonny2779** [comment]
http://ngmodules.org/modules/ng-csv

**Comment by asafdav** [comment]
Thanks, I updated the description there.
