### ISSUE TITLE
Decimal Separator

### ISSUE THREAD

**Issue by n0n3br** [asafdav/ng-csv#86]
I'm trying to use the decimal-separator option (decimal-separator=',') to change from period to colon, but I can't get it to work. I've also inspected the code and cant seem to find any reference to it. 

Can you post an working example of code using this option ?

**Comment by asafdav** [comment]
Hi, my bad. I didn't push a build that includes this feature, just did. 
it's a good idea to add an example, would you like to pull request ? 
you can base it on the test cases.
