### ISSUE TITLE
ng-click compatibility

### ISSUE THREAD

**Issue by cstephe** [asafdav/ng-csv#9]
I apologize if this is dumb.  However, I'm using the directive as part of a dialog where the button to both export as csv and close the dialog is the same.  on plunker ngcsv seems to ignore the ng-click.  When used with angular bootstrap there are a bunch of errors.   If there is a beforeExport and afterExport or some such I think that would help with compatibility.

RIght now I'm doing this.

```
  <div ng-csv="csvData" csv-header="colsToExport" filename="{{exportFileName}}">
    <button class="btn btn-primary" ng-click="ok()">OK</button>
  </div>
```

Where the div tightly wraps the button, because of event bubbling my ok method is preparing the csvData before the ngcsv sees the click basically giving me a beforeExport.

**Comment by sumit89** [comment]
Can u please provide the URL from where we can get this version (v0.0.6)
