### ISSUE TITLE
MAJOR performance improvement by changing one line.

### ISSUE THREAD

**Issue by pursual** [asafdav/ng-csv#95]
In the csv-service.js get rid of:
`responseData = angular.copy(responseData);`

Instead do it at the time of row creation:

`angular.forEach(arrData, function (oldNoLongerUsedRow, index) {`
`    var row = angular.copy(arrData[index]);`
`     var dataString, infoArray;...`

**Comment by asafdav** [comment]
Can you please pull request ?

**Comment by pursual** [comment]
I'll try.

**Comment by pursual** [comment]
Submitted. #96

**Comment by asafdav** [comment]
Great stuff, thank you!
