### ISSUE TITLE
add color to csv column 

### ISSUE THREAD

**Issue by YahiaDev** [asafdav/ng-csv#98]
I'm using ng-csv to export csv files.

i have to following object to be exported into csv file.

myObj = {position:"", status:""};
the status fild can have a different values: "X" or "Y" ....

So if the status field is equal to "X", the csv file column containing the X value has a red background color, and if the status field is equal to "Y", the xls column containing the Y value has a green background color.

How can i do this using the angulars ng-csv ?

my ns-csv is declared us following:

<button ng-csv="getCSVExport(currentgrid)" csv-header="headersCsv" filename="matrice_chantier.csv" field-separator=";" decimal-separator="." class="btn btn-default exportCSV" style="margin:0; display:inline-block;" 
add-bom="true"><img class="imgCSV" style="margin:0; max-width:15px;" 
src="/img/csv.jpg" alt="Export to CSV">
</button>

**Comment by asafdav** [comment]
CSV is a raw text file with no formatting at all, as long as you export a csv file you can't do it.

**Comment by HariBabuThubati** [comment]
I'm using ng-csv to export csv ,
If the coloumn have number it is aligning left and if coloumn have char aligning right , i want to align to left only. and 89417E109 is displaying as 8.94E+113 , please advise.
